"""Item database with all game items."""
from typing import Dict, Any
from game.loot_system import LootRarity


class ItemType:
    """Item type categories."""
    WEAPON = "weapon"
    ARMOR = "armor"
    ACCESSORY = "accessory"
    CONSUMABLE = "consumable"
    MATERIAL = "material"
    QUEST = "quest"
    CURRENCY = "currency"


# Complete item database
ITEM_DATABASE: Dict[str, Dict[str, Any]] = {
    # ===== WEAPONS =====
    "rusty_sword": {
        "name": "Rusty Sword",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.COMMON,
        "damage": 5,
        "description": "An old, rusted blade. Better than nothing.",
        "level_required": 1,
        "value": 10,
    },
    "iron_sword": {
        "name": "Iron Sword",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.COMMON,
        "damage": 15,
        "description": "A sturdy iron sword.",
        "level_required": 1,
        "value": 50,
    },
    "steel_sword": {
        "name": "Steel Sword",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.UNCOMMON,
        "damage": 25,
        "description": "A well-crafted steel blade.",
        "level_required": 5,
        "value": 150,
    },
    "forest_blade": {
        "name": "Forest Blade",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.LEGENDARY,
        "damage": 60,
        "description": "A legendary blade infused with nature's power.",
        "level_required": 15,
        "value": 2000,
        "special": "Deals bonus damage to undead",
    },
    "crystal_blade": {
        "name": "Crystal Blade",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.LEGENDARY,
        "damage": 65,
        "description": "A blade forged from pure crystal.",
        "level_required": 20,
        "value": 2500,
        "special": "Ignores 20% of enemy defense",
    },
    "reinforced_iron_sword": {
        "name": "Reinforced Iron Sword",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.UNCOMMON,
        "damage": 20,
        "description": "An iron sword reinforced with steel.",
        "level_required": 3,
        "value": 100,
    },
    "iron_pickaxe": {
        "name": "Iron Pickaxe",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.COMMON,
        "damage": 8,
        "description": "A tool for mining ore.",
        "level_required": 1,
        "value": 40,
    },
    "wooden_club": {
        "name": "Wooden Club",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.COMMON,
        "damage": 3,
        "description": "A crude wooden club.",
        "level_required": 1,
        "value": 5,
    },
    "sky_blade": {
        "name": "Sky Blade",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.EPIC,
        "damage": 55,
        "description": "A blade infused with the power of the skies.",
        "level_required": 18,
        "value": 1800,
        "special": "Increased critical hit chance",
    },
    "necromancer_staff": {
        "name": "Necromancer Staff",
        "type": ItemType.WEAPON,
        "rarity": LootRarity.LEGENDARY,
        "damage": 45,
        "description": "A staff crackling with necromantic energy.",
        "level_required": 25,
        "value": 3000,
        "special": "Drains life from enemies",
    },

    # ===== ARMOR =====
    "leather_armor": {
        "name": "Leather Armor",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.COMMON,
        "defense": 10,
        "description": "Basic leather protection.",
        "level_required": 1,
        "value": 40,
    },
    "iron_armor": {
        "name": "Iron Armor",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.UNCOMMON,
        "defense": 20,
        "description": "Sturdy iron plate armor.",
        "level_required": 5,
        "value": 120,
    },
    "chainmail": {
        "name": "Chainmail Armor",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.UNCOMMON,
        "defense": 25,
        "description": "Flexible chainmail protection.",
        "level_required": 4,
        "value": 150,
    },
    "crystal_plate": {
        "name": "Crystal Plate Armor",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.EPIC,
        "defense": 50,
        "health": 30,
        "description": "Magical armor forged from crystals.",
        "level_required": 9,
        "value": 800,
    },
    "tattered_clothes": {
        "name": "Tattered Clothes",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.COMMON,
        "defense": 2,
        "description": "Worn and tattered clothing. Better than nothing.",
        "level_required": 1,
        "value": 3,
    },
    "ancient_plate": {
        "name": "Ancient Plate Armor",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.EPIC,
        "defense": 60,
        "health": 50,
        "description": "Ancient armor with mysterious engravings.",
        "level_required": 12,
        "value": 1200,
        "special": "Increases stamina regeneration",
    },
    "forest_garb": {
        "name": "Forest Garb",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.UNCOMMON,
        "defense": 18,
        "description": "Light armor made from forest materials.",
        "level_required": 6,
        "value": 200,
    },
    "sky_mantle": {
        "name": "Sky Mantle",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.RARE,
        "defense": 35,
        "stamina": 20,
        "description": "A cloak woven from sky essence.",
        "level_required": 10,
        "value": 650,
    },
    "crystal_armor": {
        "name": "Crystal Armor",
        "type": ItemType.ARMOR,
        "rarity": LootRarity.LEGENDARY,
        "defense": 70,
        "health": 60,
        "description": "Legendary armor forged from perfect crystals.",
        "level_required": 25,
        "value": 3500,
        "special": "Reflects 10% of damage taken",
    },

    # ===== ACCESSORIES =====
    "bronze_ring": {
        "name": "Bronze Ring",
        "type": ItemType.ACCESSORY,
        "rarity": LootRarity.COMMON,
        "defense": 3,
        "description": "A simple bronze ring.",
        "level_required": 1,
        "value": 20,
    },
    "silver_amulet": {
        "name": "Silver Amulet",
        "type": ItemType.ACCESSORY,
        "rarity": LootRarity.UNCOMMON,
        "health": 15,
        "description": "A silver amulet that provides protection.",
        "level_required": 4,
        "value": 100,
    },
    "power_ring": {
        "name": "Power Ring",
        "type": ItemType.ACCESSORY,
        "rarity": LootRarity.RARE,
        "damage": 10,
        "description": "A ring that enhances physical power.",
        "level_required": 7,
        "value": 300,
    },
    "nature_amulet": {
        "name": "Nature Amulet",
        "type": ItemType.ACCESSORY,
        "rarity": LootRarity.LEGENDARY,
        "health": 40,
        "defense": 15,
        "description": "An amulet blessed by the forest guardian.",
        "level_required": 20,
        "value": 2500,
        "special": "Slowly regenerates health",
    },
    "dark_grimoire": {
        "name": "Dark Grimoire",
        "type": ItemType.ACCESSORY,
        "rarity": LootRarity.LEGENDARY,
        "damage": 25,
        "description": "An ancient book of forbidden knowledge.",
        "level_required": 25,
        "value": 2800,
        "special": "Increases spell power",
    },

    # ===== CONSUMABLES =====
    "health_potion": {
        "name": "Health Potion",
        "type": ItemType.CONSUMABLE,
        "rarity": LootRarity.COMMON,
        "description": "Restores 50 health.",
        "value": 25,
        "stackable": True,
        "max_stack": 20,
        "healing": 50,
    },
    "greater_health_potion": {
        "name": "Greater Health Potion",
        "type": ItemType.CONSUMABLE,
        "rarity": LootRarity.RARE,
        "description": "Restores 150 health.",
        "value": 80,
        "stackable": True,
        "max_stack": 20,
        "healing": 150,
    },
    "stamina_potion": {
        "name": "Stamina Potion",
        "type": ItemType.CONSUMABLE,
        "rarity": LootRarity.COMMON,
        "description": "Restores 30 stamina.",
        "value": 20,
        "stackable": True,
        "max_stack": 20,
        "stamina_restore": 30,
    },

    # ===== MATERIALS =====
    "wolf_pelt": {
        "name": "Wolf Pelt",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "Fur from a wolf. Can be sold or crafted.",
        "value": 15,
        "stackable": True,
        "max_stack": 50,
    },
    "bear_pelt": {
        "name": "Bear Pelt",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Thick fur from a bear.",
        "value": 40,
        "stackable": True,
        "max_stack": 50,
    },
    "raw_meat": {
        "name": "Raw Meat",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "Fresh meat from an animal.",
        "value": 8,
        "stackable": True,
        "max_stack": 50,
    },
    "spirit_essence": {
        "name": "Spirit Essence",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Essence from a forest spirit.",
        "value": 60,
        "stackable": True,
        "max_stack": 50,
    },
    "crystal_shard": {
        "name": "Crystal Shard",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "A shard of crystal.",
        "value": 70,
        "stackable": True,
        "max_stack": 50,
    },
    "wolf_fang": {
        "name": "Wolf Fang",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Sharp fang from a wolf.",
        "value": 25,
        "stackable": True,
        "max_stack": 50,
    },
    "iron_ingot": {
        "name": "Iron Ingot",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "A bar of refined iron.",
        "value": 30,
        "stackable": True,
        "max_stack": 50,
    },
    "steel_ingot": {
        "name": "Steel Ingot",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "A bar of refined steel.",
        "value": 80,
        "stackable": True,
        "max_stack": 50,
    },
    "leather_strip": {
        "name": "Leather Strips",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "Strips of leather for crafting.",
        "value": 5,
        "stackable": True,
        "max_stack": 99,
    },
    "coal": {
        "name": "Coal",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "Used for smelting and crafting.",
        "value": 10,
        "stackable": True,
        "max_stack": 99,
    },
    "wooden_stick": {
        "name": "Wooden Stick",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "A simple wooden stick.",
        "value": 2,
        "stackable": True,
        "max_stack": 99,
    },
    "magic_essence": {
        "name": "Magic Essence",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.RARE,
        "description": "Raw magical energy.",
        "value": 150,
        "stackable": True,
        "max_stack": 50,
    },
    "red_herb": {
        "name": "Red Herb",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "A healing herb with red leaves.",
        "value": 12,
        "stackable": True,
        "max_stack": 99,
    },
    "blue_herb": {
        "name": "Blue Herb",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "An herb that restores stamina.",
        "value": 10,
        "stackable": True,
        "max_stack": 99,
    },
    "ancient_herb": {
        "name": "Ancient Herb",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.RARE,
        "description": "A rare herb with powerful properties.",
        "value": 100,
        "stackable": True,
        "max_stack": 50,
    },
    "bear_claw": {
        "name": "Bear Claw",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Sharp claw from a bear.",
        "value": 35,
        "stackable": True,
        "max_stack": 50,
    },
    "magic_dust": {
        "name": "Magic Dust",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Shimmering magical dust.",
        "value": 50,
        "stackable": True,
        "max_stack": 50,
    },
    "forest_crystal": {
        "name": "Forest Crystal",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.RARE,
        "description": "A crystal infused with forest magic.",
        "value": 120,
        "stackable": True,
        "max_stack": 50,
    },
    "wisp_essence": {
        "name": "Wisp Essence",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Ethereal essence from a wisp.",
        "value": 45,
        "stackable": True,
        "max_stack": 50,
    },
    "crystal_core": {
        "name": "Crystal Core",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.RARE,
        "description": "The heart of a crystal golem.",
        "value": 200,
        "stackable": True,
        "max_stack": 20,
    },
    "rare_gem": {
        "name": "Rare Gem",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.EPIC,
        "description": "An exceptionally rare gemstone.",
        "value": 500,
        "stackable": True,
        "max_stack": 20,
    },
    "bat_wing": {
        "name": "Bat Wing",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "Leathery wing from a cave bat.",
        "value": 8,
        "stackable": True,
        "max_stack": 50,
    },
    "serpent_scale": {
        "name": "Serpent Scale",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Shimmering scale from a sky serpent.",
        "value": 65,
        "stackable": True,
        "max_stack": 50,
    },
    "sky_essence": {
        "name": "Sky Essence",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.RARE,
        "description": "Pure essence of the sky.",
        "value": 180,
        "stackable": True,
        "max_stack": 50,
    },
    "serpent_fang": {
        "name": "Serpent Fang",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Venomous fang from a serpent.",
        "value": 55,
        "stackable": True,
        "max_stack": 50,
    },
    "wind_essence": {
        "name": "Wind Essence",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Essence of wind and air.",
        "value": 70,
        "stackable": True,
        "max_stack": 50,
    },
    "elemental_core": {
        "name": "Elemental Core",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.RARE,
        "description": "Core of an elemental being.",
        "value": 220,
        "stackable": True,
        "max_stack": 20,
    },
    "ancient_bone": {
        "name": "Ancient Bone",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Ancient bone from undead.",
        "value": 40,
        "stackable": True,
        "max_stack": 50,
    },
    "cursed_essence": {
        "name": "Cursed Essence",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.UNCOMMON,
        "description": "Dark essence tainted by curses.",
        "value": 85,
        "stackable": True,
        "max_stack": 50,
    },
    "ancient_artifact": {
        "name": "Ancient Artifact",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.EPIC,
        "description": "A mysterious artifact from ancient times.",
        "value": 600,
        "stackable": True,
        "max_stack": 10,
    },
    "bone": {
        "name": "Bone",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.COMMON,
        "description": "A simple bone.",
        "value": 5,
        "stackable": True,
        "max_stack": 99,
    },
    "guardian_heart": {
        "name": "Guardian Heart",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.LEGENDARY,
        "description": "The heart of a forest guardian.",
        "value": 1000,
        "stackable": True,
        "max_stack": 5,
    },
    "legendary_wood": {
        "name": "Legendary Wood",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.LEGENDARY,
        "description": "Ancient wood from the sacred forest.",
        "value": 800,
        "stackable": True,
        "max_stack": 10,
    },
    "crystal_crown": {
        "name": "Crystal Crown",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.LEGENDARY,
        "description": "Crown of the crystal king.",
        "value": 1500,
        "stackable": True,
        "max_stack": 1,
    },
    "perfect_crystal": {
        "name": "Perfect Crystal",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.EPIC,
        "description": "A flawless crystal of immense power.",
        "value": 900,
        "stackable": True,
        "max_stack": 10,
    },
    "lich_phylactery": {
        "name": "Lich Phylactery",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.LEGENDARY,
        "description": "The source of a lich's immortality.",
        "value": 2000,
        "stackable": True,
        "max_stack": 1,
    },
    "death_essence": {
        "name": "Death Essence",
        "type": ItemType.MATERIAL,
        "rarity": LootRarity.EPIC,
        "description": "Pure essence of death and decay.",
        "value": 750,
        "stackable": True,
        "max_stack": 20,
    },

    # ===== CURRENCY =====
    "gold": {
        "name": "Gold",
        "type": ItemType.CURRENCY,
        "rarity": LootRarity.COMMON,
        "description": "Currency used throughout the land.",
        "value": 1,
        "stackable": True,
        "max_stack": 9999,
    },
}


def get_item(item_id: str) -> Dict[str, Any]:
    """Get item data by ID."""
    return ITEM_DATABASE.get(item_id)


def get_item_name(item_id: str) -> str:
    """Get display name for an item."""
    item = get_item(item_id)
    return item["name"] if item else "Unknown Item"


def get_items_by_rarity(rarity: LootRarity) -> list:
    """
    Get all items of a specific rarity.

    Args:
        rarity: The rarity level to filter by

    Returns:
        List of item objects with matching rarity (each with 'id' field added)
    """
    items = []
    for item_id, item_data in ITEM_DATABASE.items():
        if item_data.get("rarity") == rarity:
            # Create item object with id field
            item_obj = type('Item', (), {'id': item_id, **item_data})()
            items.append(item_obj)
    return items
